import csv
import re
from urllib.parse import unquote

# This HTML is a form with hidden inputs like rdata0, rdata1, etc.
# Note: Name is not explicitly in the hidden inputs per record, but zone_name is.
# Some records might be for the apex (zone_name).

html_content = """
<form enctype="application/x-www-form-urlencoded" method="post" onsubmit=";onSubmit(this);" name="myform" action="/tmui/Control/form" id="myform">
... (rest of the HTML provided by user) ...
"""

# Since I have the full text from the previous message, I will parse the hidden inputs.
# The inputs follow a pattern: name="view_nameN", name="zone_nameN", name="ttlN", name="rr_typeN", name="rdataN"

# Regular expression to find all hidden inputs with their name and value
input_pattern = re.compile(r'<input name="(.*?)" type="hidden" value="(.*?)">')

# Extract all matches
matches = input_pattern.findall("""<input name="view_name0" type="hidden" value="external">
<input name="zone_name0" type="hidden" value="chilquinta.cl.">
<input name="ttl0" type="hidden" value="0">
<input name="rr_type0" type="hidden" value="TXT">
<input name="rdata0" type="hidden" value="%22k%3Drsa%5C%3B+p%3DMIGfMA0GCSqGSIb3DQEBAQUAA4GNADCBiQKBgQC7h0kCkjlBBr01BROvgfID61UvZkuxCAzvaxH5ManQdMmEBHVunHiqZqq3zvP3C72ROCJuhIhnPfIsdXjiTLdQ9Mib5uE6vo2p6Md2WH86xZuMH%2BDdgXD%2F%2Bsz4ihvDEGrsPWexK%2FRHdeBQ3P%2Bl%2BV1X1jZFFgG9CzU%2B8Jy3XPanAwIDAQAB%22">
<input name="view_name1" type="hidden" value="external">
<input name="zone_name1" type="hidden" value="chilquinta.cl.">
<input name="ttl1" type="hidden" value="0">
<input name="rr_type1" type="hidden" value="TXT">
<input name="rdata1" type="hidden" value="%22v%3DDKIM1%5C%3B+g%3D*%5C%3B+k%3Drsa%5C%3B+p%3DMIGfMA0GCSqGSIb3DQEBAQUAA4GNADCBiQKBgQDNS2HyFed4hCWN9FwvLXs26QO3hQH9FMGTEy%2Fi5DBjV4CC%2FpYY%2FZeq%2FUP7GYb%2F37S5CXE%2Bi1EhIvYodfxWJ5nJneYcjE%2Bpp0zjhoqNJ%2FtQD5vY5yQKDoLanztx%2BnRzz4o7J96fYXYhqB2BV3tr2dG0F66yRzZEzVyryyPOuy5MCQIDAQAB%22">
<input name="view_name2" type="hidden" value="external">
<input name="zone_name2" type="hidden" value="chilquinta.cl.">
<input name="ttl2" type="hidden" value="3600">
<input name="rr_type2" type="hidden" value="TXT">
<input name="rdata2" type="hidden" value="%22v%3DDMARC1%5C%3B+p%3Dquarantine%5C%3B+rua%3Dmailto%3Apostmaster%40chilquinta.cl%22">
<input name="view_name3" type="hidden" value="external">
<input name="zone_name3" type="hidden" value="chilquinta.cl.">
<input name="ttl3" type="hidden" value="0">
<input name="rr_type3" type="hidden" value="TXT">
<input name="rdata3" type="hidden" value="%22+6c4e3428d229ce00414ac9ae0dfa896d%22">
<input name="view_name4" type="hidden" value="external">
<input name="zone_name4" type="hidden" value="chilquinta.cl.">
<input name="ttl4" type="hidden" value="3600">
<input name="rr_type4" type="hidden" value="TXT">
<input name="rdata4" type="hidden" value="%225ecdadc95ee5561e693c66e429169cd4%22">
<input name="view_name5" type="hidden" value="external">
<input name="zone_name5" type="hidden" value="chilquinta.cl.">
<input name="ttl5" type="hidden" value="0">
<input name="rr_type5" type="hidden" value="TXT">
<input name="rdata5" type="hidden" value="%22v%3Dspf1+include%3Aspf.protection.outlook.com+include%3Asendgrid.net+include%3Aamazonses.com+a+mx+include%3Aspf.masterbase.com+include%3Aspf.mailjet.com++ip4%3A200.27.54.128%2F27+ip4%3A201.236.92.224%2F27+ip4%3A200.72.40.99+ip4%3A200.72.40.112%2F32+-all%22">
<input name="view_name6" type="hidden" value="external">
<input name="zone_name6" type="hidden" value="chilquinta.cl.">
<input name="ttl6" type="hidden" value="0">
<input name="rr_type6" type="hidden" value="TXT">
<input name="rdata6" type="hidden" value="%22ui%2FCtjieiD%2BJpQtW9L2I7MYy%2BVKVYA%2F%2FkqZpBFk5cfbHpPxmeETjahTgh3Izvb83gMxAeVf5nqEuuNVGtgPuqw%3D%3D%22">
<input name="view_name7" type="hidden" value="external">
<input name="zone_name7" type="hidden" value="chilquinta.cl.">
<input name="ttl7" type="hidden" value="0">
<input name="rr_type7" type="hidden" value="TXT">
<input name="rdata7" type="hidden" value="%22google-site-verification%3DwyxEdT_XaiZmjPBRclh-8e06OEAX1MtbrNdTMm4iN_E%22">
<input name="view_name8" type="hidden" value="external">
<input name="zone_name8" type="hidden" value="chilquinta.cl.">
<input name="ttl8" type="hidden" value="0">
<input name="rr_type8" type="hidden" value="TXT">
<input name="rdata8" type="hidden" value="%22facebook-domain-verification%3Di94b7rcm79q60qoe9zc26ige5bunok%22">
<input name="view_name9" type="hidden" value="external">
<input name="zone_name9" type="hidden" value="chilquinta.cl.">
<input name="ttl9" type="hidden" value="0">
<input name="rr_type9" type="hidden" value="TXT">
<input name="rdata9" type="hidden" value="%22MS%3D2DABE84159FA5F088A602C88A6DB11F584DACB61%22">
<input name="view_name10" type="hidden" value="external">
<input name="zone_name10" type="hidden" value="chilquinta.cl.">
<input name="ttl10" type="hidden" value="0">
<input name="rr_type10" type="hidden" value="TXT">
<input name="rdata10" type="hidden" value="%2204042023%22">
<input name="view_name11" type="hidden" value="external">
<input name="zone_name11" type="hidden" value="chilquinta.cl.">
<input name="ttl11" type="hidden" value="3600">
<input name="rr_type11" type="hidden" value="SRV">
<input name="rdata11" type="hidden" value="100+1+443+sipdir.online.lync.com.">
<input name="view_name12" type="hidden" value="external">
<input name="zone_name12" type="hidden" value="chilquinta.cl.">
<input name="ttl12" type="hidden" value="3600">
<input name="rr_type12" type="hidden" value="SRV">
<input name="rdata12" type="hidden" value="100+1+5061+sipfed.online.lync.com.">
<input name="view_name13" type="hidden" value="external">
<input name="zone_name13" type="hidden" value="chilquinta.cl.">
<input name="ttl13" type="hidden" value="0">
<input name="rr_type13" type="hidden" value="SOA">
<input name="rdata13" type="hidden" value="ns1.chilquinta.cl.+hostmaster.chilquinta.cl.+2026030202+300+300+300+300">
<input name="view_name14" type="hidden" value="external">
<input name="zone_name14" type="hidden" value="chilquinta.cl.">
<input name="ttl14" type="hidden" value="0">
<input name="rr_type14" type="hidden" value="NS">
<input name="rdata14" type="hidden" value="ns2.chilquinta.cl.">
<input name="view_name15" type="hidden" value="external">
<input name="zone_name15" type="hidden" value="chilquinta.cl.">
<input name="ttl15" type="hidden" value="0">
<input name="rr_type15" type="hidden" value="NS">
<input name="rdata15" type="hidden" value="ns1.chilquinta.cl.">
<input name="view_name16" type="hidden" value="external">
<input name="zone_name16" type="hidden" value="chilquinta.cl.">
<input name="ttl16" type="hidden" value="0">
<input name="rr_type16" type="hidden" value="MX">
<input name="rdata16" type="hidden" value="1+mx.sendgrid.net.">
<input name="view_name17" type="hidden" value="external">
<input name="zone_name17" type="hidden" value="chilquinta.cl.">
<input name="ttl17" type="hidden" value="0">
<input name="rr_type17" type="hidden" value="MX">
<input name="rdata17" type="hidden" value="10+mx1.chilquinta.cl.">
<input name="view_name18" type="hidden" value="external">
<input name="zone_name18" type="hidden" value="chilquinta.cl.">
<input name="ttl18" type="hidden" value="0">
<input name="rr_type18" type="hidden" value="MX">
<input name="rdata18" type="hidden" value="10+mx.chilquinta.cl.">
<input name="view_name19" type="hidden" value="external">
<input name="zone_name19" type="hidden" value="chilquinta.cl.">
<input name="ttl19" type="hidden" value="3600">
<input name="rr_type19" type="hidden" value="MX">
<input name="rdata19" type="hidden" value="0+chilquinta-cl.mail.protection.outlook.com.">
<input name="view_name20" type="hidden" value="external">
<input name="zone_name20" type="hidden" value="chilquinta.cl.">
<input name="ttl20" type="hidden" value="0">
<input name="rr_type20" type="hidden" value="CNAME">
<input name="rdata20" type="hidden" value="d13icpz12iqfz.cloudfront.net.">
<input name="view_name21" type="hidden" value="external">
<input name="zone_name21" type="hidden" value="chilquinta.cl.">
<input name="ttl21" type="hidden" value="3600">
<input name="rr_type21" type="hidden" value="CNAME">
<input name="rdata21" type="hidden" value="sipdir.online.lync.com.">
<input name="view_name22" type="hidden" value="external">
<input name="zone_name22" type="hidden" value="chilquinta.cl.">
<input name="ttl22" type="hidden" value="3600">
<input name="rr_type22" type="hidden" value="CNAME">
<input name="rdata22" type="hidden" value="sg2.v3108867.c308454725.e.marketingautomation.services.">
<input name="view_name23" type="hidden" value="external">
<input name="zone_name23" type="hidden" value="chilquinta.cl.">
<input name="ttl23" type="hidden" value="0">
<input name="rr_type23" type="hidden" value="CNAME">
<input name="rdata23" type="hidden" value="d1yhbyqbicsoct.cloudfront.net.">
<input name="view_name24" type="hidden" value="external">
<input name="zone_name24" type="hidden" value="chilquinta.cl.">
<input name="ttl24" type="hidden" value="3600">
<input name="rr_type24" type="hidden" value="CNAME">
<input name="rdata24" type="hidden" value="webdir.online.lync.com.">
<input name="view_name25" type="hidden" value="external">
<input name="zone_name25" type="hidden" value="chilquinta.cl.">
<input name="ttl25" type="hidden" value="3600">
<input name="rr_type25" type="hidden" value="CNAME">
<input name="rdata25" type="hidden" value="chilquintacl.sharepoint.com%2Fsites%2FSGDC%2FApp%2Findex.aspx.">
<input name="view_name26" type="hidden" value="external">
<input name="zone_name26" type="hidden" value="chilquinta.cl.">
<input name="ttl26" type="hidden" value="3600">
<input name="rr_type26" type="hidden" value="CNAME">
<input name="rdata26" type="hidden" value="enterpriseregistration.windows.net.">
<input name="view_name27" type="hidden" value="external">
<input name="zone_name27" type="hidden" value="chilquinta.cl.">
<input name="ttl27" type="hidden" value="3600">
<input name="rr_type27" type="hidden" value="CNAME">
<input name="rdata27" type="hidden" value="enterpriseenrollment.manage.microsoft.com.">
<input name="view_name28" type="hidden" value="external">
<input name="zone_name28" type="hidden" value="chilquinta.cl.">
<input name="ttl28" type="hidden" value="3600">
<input name="rr_type28" type="hidden" value="CNAME">
<input name="rdata28" type="hidden" value="u2140324.wl075.sendgrid.net.">
<input name="view_name29" type="hidden" value="external">
<input name="zone_name29" type="hidden" value="chilquinta.cl.">
<input name="ttl29" type="hidden" value="3600">
<input name="rr_type29" type="hidden" value="CNAME">
<input name="rdata29" type="hidden" value="autodiscover.outlook.com.">
<input name="view_name30" type="hidden" value="external">
<input name="zone_name30" type="hidden" value="chilquinta.cl.">
<input name="ttl30" type="hidden" value="0">
<input name="rr_type30" type="hidden" value="CNAME">
<input name="rdata30" type="hidden" value="autodiscover.outlook.com.">
<input name="view_name31" type="hidden" value="external">
<input name="zone_name31" type="hidden" value="chilquinta.cl.">
<input name="ttl31" type="hidden" value="3600">
<input name="rr_type31" type="hidden" value="CNAME">
<input name="rdata31" type="hidden" value="selector2-chilquinta-cl._domainkey.chilquintacl.onmicrosoft.com.">
<input name="view_name32" type="hidden" value="external">
<input name="zone_name32" type="hidden" value="chilquinta.cl.">
<input name="ttl32" type="hidden" value="3600">
<input name="rr_type32" type="hidden" value="CNAME">
<input name="rdata32" type="hidden" value="selector1-chilquinta-cl._domainkey.chilquintacl.onmicrosoft.com.">
<input name="view_name33" type="hidden" value="external">
<input name="zone_name33" type="hidden" value="chilquinta.cl.">
<input name="ttl33" type="hidden" value="3600">
<input name="rr_type33" type="hidden" value="CNAME">
<input name="rdata33" type="hidden" value="s2.domainkey.u2140324.wl075.sendgrid.net.">
<input name="view_name34" type="hidden" value="external">
<input name="zone_name34" type="hidden" value="chilquinta.cl.">
<input name="ttl34" type="hidden" value="3600">
<input name="rr_type34" type="hidden" value="CNAME">
<input name="rdata34" type="hidden" value="s1.domainkey.u2140324.wl075.sendgrid.net.">
<input name="view_name35" type="hidden" value="external">
<input name="zone_name35" type="hidden" value="chilquinta.cl.">
<input name="ttl35" type="hidden" value="3600">
<input name="rr_type35" type="hidden" value="CNAME">
<input name="rdata35" type="hidden" value="hh5sgh6kpopyxmqudunlndsc7pvqir4g.dkim.amazonses.com.">
<input name="view_name36" type="hidden" value="external">
<input name="zone_name36" type="hidden" value="chilquinta.cl.">
<input name="ttl36" type="hidden" value="3600">
<input name="rr_type36" type="hidden" value="CNAME">
<input name="rdata36" type="hidden" value="af4n7nyf5tgax5cp2jnw4nifqbpdwexf.dkim.amazonses.com.">
<input name="view_name37" type="hidden" value="external">
<input name="zone_name37" type="hidden" value="chilquinta.cl.">
<input name="ttl37" type="hidden" value="3600">
<input name="rr_type37" type="hidden" value="CNAME">
<input name="rdata37" type="hidden" value="76os2ect4aiszcnhe7k5kld4uhij7z24.dkim.amazonses.com.">
<input name="view_name38" type="hidden" value="external">
<input name="zone_name38" type="hidden" value="chilquinta.cl.">
<input name="ttl38" type="hidden" value="0">
<input name="rr_type38" type="hidden" value="A">
<input name="rdata38" type="hidden" value="186.67.105.154">
<input name="view_name39" type="hidden" value="external">
<input name="zone_name39" type="hidden" value="chilquinta.cl.">
<input name="ttl39" type="hidden" value="0">
<input name="rr_type39" type="hidden" value="A">
<input name="rdata39" type="hidden" value="200.72.40.117">
<input name="view_name40" type="hidden" value="external">
<input name="zone_name40" type="hidden" value="chilquinta.cl.">
<input name="ttl40" type="hidden" value="0">
<input name="rr_type40" type="hidden" value="A">
<input name="rdata40" type="hidden" value="200.72.40.117">
<input name="view_name41" type="hidden" value="external">
<input name="zone_name41" type="hidden" value="chilquinta.cl.">
<input name="ttl41" type="hidden" value="0">
<input name="rr_type41" type="hidden" value="A">
<input name="rdata41" type="hidden" value="200.72.40.117">
<input name="view_name42" type="hidden" value="external">
<input name="zone_name42" type="hidden" value="chilquinta.cl.">
<input name="ttl42" type="hidden" value="0">
<input name="rr_type42" type="hidden" value="A">
<input name="rdata42" type="hidden" value="200.72.40.117">
<input name="view_name43" type="hidden" value="external">
<input name="zone_name43" type="hidden" value="chilquinta.cl.">
<input name="ttl43" type="hidden" value="0">
<input name="rr_type43" type="hidden" value="A">
<input name="rdata43" type="hidden" value="186.67.176.229">
<input name="view_name44" type="hidden" value="external">
<input name="zone_name44" type="hidden" value="chilquinta.cl.">
<input name="ttl44" type="hidden" value="0">
<input name="rr_type44" type="hidden" value="A">
<input name="rdata44" type="hidden" value="200.72.40.106">
<input name="view_name45" type="hidden" value="external">
<input name="zone_name45" type="hidden" value="chilquinta.cl.">
<input name="ttl45" type="hidden" value="0">
<input name="rr_type45" type="hidden" value="A">
<input name="rdata45" type="hidden" value="200.72.40.106">
<input name="view_name46" type="hidden" value="external">
<input name="zone_name46" type="hidden" value="chilquinta.cl.">
<input name="ttl46" type="hidden" value="3600">
<input name="rr_type46" type="hidden" value="A">
<input name="rdata46" type="hidden" value="200.72.40.111">
<input name="view_name47" type="hidden" value="external">
<input name="zone_name47" type="hidden" value="chilquinta.cl.">
<input name="ttl47" type="hidden" value="0">
<input name="rr_type47" type="hidden" value="A">
<input name="rdata47" type="hidden" value="190.153.249.201">
<input name="view_name48" type="hidden" value="external">
<input name="zone_name48" type="hidden" value="chilquinta.cl.">
<input name="ttl48" type="hidden" value="0">
<input name="rr_type48" type="hidden" value="A">
<input name="rdata48" type="hidden" value="200.72.40.104">
<input name="view_name49" type="hidden" value="external">
<input name="zone_name49" type="hidden" value="chilquinta.cl.">
<input name="ttl49" type="hidden" value="0">
<input name="rr_type49" type="hidden" value="A">
<input name="rdata49" type="hidden" value="186.67.176.229">
<input name="view_name50" type="hidden" value="external">
<input name="zone_name50" type="hidden" value="chilquinta.cl.">
<input name="ttl50" type="hidden" value="0">
<input name="rr_type50" type="hidden" value="A">
<input name="rdata50" type="hidden" value="200.72.40.120">
<input name="view_name51" type="hidden" value="external">
<input name="zone_name51" type="hidden" value="chilquinta.cl.">
<input name="ttl51" type="hidden" value="3600">
<input name="rr_type51" type="hidden" value="A">
<input name="rdata51" type="hidden" value="190.153.249.194">
<input name="view_name52" type="hidden" value="external">
<input name="zone_name52" type="hidden" value="chilquinta.cl.">
<input name="ttl52" type="hidden" value="3600">
<input name="rr_type52" type="hidden" value="A">
<input name="rdata52" type="hidden" value="186.67.176.229">
<input name="view_name53" type="hidden" value="external">
<input name="zone_name53" type="hidden" value="chilquinta.cl.">
<input name="ttl53" type="hidden" value="60">
<input name="rr_type53" type="hidden" value="A">
<input name="rdata53" type="hidden" value="200.72.40.112">
<input name="view_name54" type="hidden" value="external">
<input name="zone_name54" type="hidden" value="chilquinta.cl.">
<input name="ttl54" type="hidden" value="3600">
<input name="rr_type54" type="hidden" value="A">
<input name="rdata54" type="hidden" value="186.67.176.236">
<input name="view_name55" type="hidden" value="external">
<input name="zone_name55" type="hidden" value="chilquinta.cl.">
<input name="ttl55" type="hidden" value="0">
<input name="rr_type55" type="hidden" value="A">
<input name="rdata55" type="hidden" value="200.72.40.117">
<input name="view_name56" type="hidden" value="external">
<input name="zone_name56" type="hidden" value="chilquinta.cl.">
<input name="ttl56" type="hidden" value="0">
<input name="rr_type56" type="hidden" value="A">
<input name="rdata56" type="hidden" value="200.72.40.124">
<input name="view_name57" type="hidden" value="external">
<input name="zone_name57" type="hidden" value="chilquinta.cl.">
<input name="ttl57" type="hidden" value="0">
<input name="rr_type57" type="hidden" value="A">
<input name="rdata57" type="hidden" value="200.72.40.116">
<input name="view_name58" type="hidden" value="external">
<input name="zone_name58" type="hidden" value="chilquinta.cl.">
<input name="ttl58" type="hidden" value="0">
<input name="rr_type58" type="hidden" value="A">
<input name="rdata58" type="hidden" value="200.72.40.117">
<input name="view_name59" type="hidden" value="external">
<input name="zone_name59" type="hidden" value="chilquinta.cl.">
<input name="ttl59" type="hidden" value="500">
<input name="rr_type59" type="hidden" value="A">
<input name="rdata59" type="hidden" value="200.72.40.117">
<input name="view_name60" type="hidden" value="external">
<input name="zone_name60" type="hidden" value="chilquinta.cl.">
<input name="ttl60" type="hidden" value="3600">
<input name="rr_type60" type="hidden" value="A">
<input name="rdata60" type="hidden" value="200.72.40.117">
<input name="view_name61" type="hidden" value="external">
<input name="zone_name61" type="hidden" value="chilquinta.cl.">
<input name="ttl61" type="hidden" value="500">
<input name="rr_type61" type="hidden" value="A">
<input name="rdata61" type="hidden" value="200.72.40.117">
<input name="view_name62" type="hidden" value="external">
<input name="zone_name62" type="hidden" value="chilquinta.cl.">
<input name="ttl62" type="hidden" value="0">
<input name="rr_type62" type="hidden" value="A">
<input name="rdata62" type="hidden" value="200.72.40.104">
<input name="view_name63" type="hidden" value="external">
<input name="zone_name63" type="hidden" value="chilquinta.cl.">
<input name="ttl63" type="hidden" value="0">
<input name="rr_type63" type="hidden" value="A">
<input name="rdata63" type="hidden" value="190.153.249.200">
<input name="view_name64" type="hidden" value="external">
<input name="zone_name64" type="hidden" value="chilquinta.cl.">
<input name="ttl64" type="hidden" value="0">
<input name="rr_type64" type="hidden" value="A">
<input name="rdata64" type="hidden" value="186.67.105.158">
<input name="view_name65" type="hidden" value="external">
<input name="zone_name65" type="hidden" value="chilquinta.cl.">
<input name="ttl65" type="hidden" value="0">
<input name="rr_type65" type="hidden" value="A">
<input name="rdata65" type="hidden" value="200.72.40.120">
<input name="view_name66" type="hidden" value="external">
<input name="zone_name66" type="hidden" value="chilquinta.cl.">
<input name="ttl66" type="hidden" value="0">
<input name="rr_type66" type="hidden" value="A">
<input name="rdata66" type="hidden" value="200.72.40.116">
<input name="view_name67" type="hidden" value="external">
<input name="zone_name67" type="hidden" value="chilquinta.cl.">
<input name="ttl67" type="hidden" value="0">
<input name="rr_type67" type="hidden" value="A">
<input name="rdata67" type="hidden" value="200.31.52.122">
<input name="view_name68" type="hidden" value="external">
<input name="zone_name68" type="hidden" value="chilquinta.cl.">
<input name="ttl68" type="hidden" value="0">
<input name="rr_type68" type="hidden" value="A">
<input name="rdata68" type="hidden" value="200.72.40.120">
<input name="view_name69" type="hidden" value="external">
<input name="zone_name69" type="hidden" value="chilquinta.cl.">
<input name="ttl69" type="hidden" value="3600">
<input name="rr_type69" type="hidden" value="A">
<input name="rdata69" type="hidden" value="200.72.40.109">
<input name="view_name70" type="hidden" value="external">
<input name="zone_name70" type="hidden" value="chilquinta.cl.">
<input name="ttl70" type="hidden" value="3600">
<input name="rr_type70" type="hidden" value="A">
<input name="rdata70" type="hidden" value="200.72.40.120">
<input name="view_name71" type="hidden" value="external">
<input name="zone_name71" type="hidden" value="chilquinta.cl.">
<input name="ttl71" type="hidden" value="0">
<input name="rr_type71" type="hidden" value="A">
<input name="rdata71" type="hidden" value="200.72.40.122">
<input name="view_name72" type="hidden" value="external">
<input name="zone_name72" type="hidden" value="chilquinta.cl.">
<input name="ttl72" type="hidden" value="0">
<input name="rr_type72" type="hidden" value="A">
<input name="rdata72" type="hidden" value="200.72.40.107">
<input name="view_name73" type="hidden" value="external">
<input name="zone_name73" type="hidden" value="chilquinta.cl.">
<input name="ttl73" type="hidden" value="0">
<input name="rr_type73" type="hidden" value="A">
<input name="rdata73" type="hidden" value="200.72.40.119">
<input name="view_name74" type="hidden" value="external">
<input name="zone_name74" type="hidden" value="chilquinta.cl.">
<input name="ttl74" type="hidden" value="0">
<input name="rr_type74" type="hidden" value="A">
<input name="rdata74" type="hidden" value="200.72.40.105">
<input name="view_name75" type="hidden" value="external">
<input name="zone_name75" type="hidden" value="chilquinta.cl.">
<input name="ttl75" type="hidden" value="0">
<input name="rr_type75" type="hidden" value="A">
<input name="rdata75" type="hidden" value="190.153.249.194">
<input name="view_name76" type="hidden" value="external">
<input name="zone_name76" type="hidden" value="chilquinta.cl.">
<input name="ttl76" type="hidden" value="0">
<input name="rr_type76" type="hidden" value="A">
<input name="rdata76" type="hidden" value="200.72.40.115">
<input name="view_name77" type="hidden" value="external">
<input name="zone_name77" type="hidden" value="chilquinta.cl.">
<input name="ttl77" type="hidden" value="86400">
<input name="rr_type77" type="hidden" value="A">
<input name="rdata77" type="hidden" value="200.72.40.115">
<input name="view_name78" type="hidden" value="external">
<input name="zone_name78" type="hidden" value="chilquinta.cl.">
<input name="ttl78" type="hidden" value="0">
<input name="rr_type78" type="hidden" value="A">
<input name="rdata78" type="hidden" value="200.72.40.120">
<input name="view_name79" type="hidden" value="external">
<input name="zone_name79" type="hidden" value="chilquinta.cl.">
<input name="ttl79" type="hidden" value="0">
<input name="rr_type79" type="hidden" value="A">
<input name="rdata79" type="hidden" value="200.72.40.126">
<input name="view_name80" type="hidden" value="external">
<input name="zone_name80" type="hidden" value="chilquinta.cl.">
<input name="ttl80" type="hidden" value="0">
<input name="rr_type80" type="hidden" value="A">
<input name="rdata80" type="hidden" value="200.72.40.126">
<input name="view_name81" type="hidden" value="external">
<input name="zone_name81" type="hidden" value="chilquinta.cl.">
<input name="ttl81" type="hidden" value="0">
<input name="rr_type81" type="hidden" value="A">
<input name="rdata81" type="hidden" value="200.72.40.120">
<input name="view_name82" type="hidden" value="external">
<input name="zone_name82" type="hidden" value="chilquinta.cl.">
<input name="ttl82" type="hidden" value="3600">
<input name="rr_type82" type="hidden" value="A">
<input name="rdata82" type="hidden" value="200.72.40.121">
<input name="view_name83" type="hidden" value="external">
<input name="zone_name83" type="hidden" value="chilquinta.cl.">
<input name="ttl83" type="hidden" value="0">
<input name="rr_type83" type="hidden" value="A">
<input name="rdata83" type="hidden" value="200.72.40.100">
<input name="view_name84" type="hidden" value="external">
<input name="zone_name84" type="hidden" value="chilquinta.cl.">
<input name="ttl84" type="hidden" value="0">
<input name="rr_type84" type="hidden" value="A">
<input name="rdata84" type="hidden" value="200.72.40.101">
<input name="view_name85" type="hidden" value="external">
<input name="zone_name85" type="hidden" value="chilquinta.cl.">
<input name="ttl85" type="hidden" value="0">
<input name="rr_type85" type="hidden" value="A">
<input name="rdata85" type="hidden" value="200.72.40.103">
<input name="view_name86" type="hidden" value="external">
<input name="zone_name86" type="hidden" value="chilquinta.cl.">
<input name="ttl86" type="hidden" value="0">
<input name="rr_type86" type="hidden" value="A">
<input name="rdata86" type="hidden" value="200.72.40.120">
<input name="view_name87" type="hidden" value="external">
<input name="zone_name87" type="hidden" value="chilquinta.cl.">
<input name="ttl87" type="hidden" value="0">
<input name="rr_type87" type="hidden" value="A">
<input name="rdata87" type="hidden" value="200.72.40.113">
<input name="view_name88" type="hidden" value="external">
<input name="zone_name88" type="hidden" value="chilquinta.cl.">
<input name="ttl88" type="hidden" value="0">
<input name="rr_type88" type="hidden" value="A">
<input name="rdata88" type="hidden" value="200.72.40.105">
<input name="view_name89" type="hidden" value="external">
<input name="zone_name89" type="hidden" value="chilquinta.cl.">
<input name="ttl89" type="hidden" value="3600">
<input name="rr_type89" type="hidden" value="A">
<input name="rdata89" type="hidden" value="200.72.40.120">
<input name="view_name90" type="hidden" value="external">
<input name="zone_name90" type="hidden" value="chilquinta.cl.">
<input name="ttl90" type="hidden" value="3600">
<input name="rr_type90" type="hidden" value="A">
<input name="rdata90" type="hidden" value="186.67.105.158">
<input name="view_name91" type="hidden" value="external">
<input name="zone_name91" type="hidden" value="chilquinta.cl.">
<input name="ttl91" type="hidden" value="3600">
<input name="rr_type91" type="hidden" value="A">
<input name="rdata91" type="hidden" value="186.67.105.158">
<input name="view_name92" type="hidden" value="external">
<input name="zone_name92" type="hidden" value="chilquinta.cl.">
<input name="ttl92" type="hidden" value="0">
<input name="rr_type92" type="hidden" value="A">
<input name="rdata92" type="hidden" value="200.72.40.120">
<input name="view_name93" type="hidden" value="external">
<input name="zone_name93" type="hidden" value="chilquinta.cl.">
<input name="ttl93" type="hidden" value="0">
<input name="rr_type93" type="hidden" value="A">
<input name="rdata93" type="hidden" value="186.67.176.229">
<input name="view_name94" type="hidden" value="external">
<input name="zone_name94" type="hidden" value="chilquinta.cl.">
<input name="ttl94" type="hidden" value="0">
<input name="rr_type94" type="hidden" value="A">
<input name="rdata94" type="hidden" value="186.67.176.229">
<input name="view_name95" type="hidden" value="external">
<input name="zone_name95" type="hidden" value="chilquinta.cl.">
<input name="ttl95" type="hidden" value="0">
<input name="rr_type95" type="hidden" value="A">
<input name="rdata95" type="hidden" value="200.72.40.120">
<input name="view_name96" type="hidden" value="external">
<input name="zone_name96" type="hidden" value="chilquinta.cl.">
<input name="ttl96" type="hidden" value="0">
<input name="rr_type96" type="hidden" value="A">
<input name="rdata96" type="hidden" value="186.67.176.229">
<input name="view_name97" type="hidden" value="external">
<input name="zone_name97" type="hidden" value="chilquinta.cl.">
<input name="ttl97" type="hidden" value="0">
<input name="rr_type97" type="hidden" value="A">
<input name="rdata97" type="hidden" value="186.67.176.229">
<input name="view_name98" type="hidden" value="external">
<input name="zone_name98" type="hidden" value="chilquinta.cl.">
<input name="ttl98" type="hidden" value="0">
<input name="rr_type98" type="hidden" value="A">
<input name="rdata98" type="hidden" value="200.72.40.120">
<input name="view_name99" type="hidden" value="external">
<input name="zone_name99" type="hidden" value="chilquinta.cl.">
<input name="ttl99" type="hidden" value="0">
<input name="rr_type99" type="hidden" value="A">
<input name="rdata99" type="hidden" value="200.72.40.104">""")

data_by_index = {}

for name, value in matches:
    # Match something like "rdata0" or "view_name15"
    m = re.match(r'([a-z_]+)(\d+)', name)
    if m:
        field = m.group(1)
        index = int(m.group(2))
        if index not in data_by_index:
            data_by_index[index] = {}
        data_by_index[index][field] = value

records = []
for index in sorted(data_by_index.keys()):
    d = data_by_index[index]
    records.append({
        'View Name': d.get('view_name', ''),
        'Zone Name': d.get('zone_name', ''),
        'TTL': d.get('ttl', ''),
        'Type': d.get('rr_type', ''),
        'RDATA': unquote(d.get('rdata', '')).replace('+', ' ')
    })

# Sort by Zone Name and Type
records.sort(key=lambda x: (x['Zone Name'], x['Type']))

# Write to CSV
with open('/Users/claudio/Antigravity/dns_records_form.csv', 'w', newline='', encoding='utf-8') as f:
    writer = csv.DictWriter(f, fieldnames=['View Name', 'Zone Name', 'TTL', 'Type', 'RDATA'])
    writer.writeheader()
    writer.writerows(records)

print(f"Successfully extracted {len(records)} records.")
